# -*- coding: utf-8 -*-
"""key_word_detection_algo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgDYMFtto4Dw-Mq7mf7HuTpU23pZL6Sb
"""

!pip install rake_nltk

from rake_nltk import Rake
r = Rake()

mytext = '''These political trends were signs of a new time. It was a time of
profound social and economic changes. It was a time when new cities
came up and new industrialised regions developed, railways expanded
and the Industrial Revolution occurred.
Industrialisation brought men, women and children to factories. Work
hours were often long and wages were poor. Unemployment was
common, particularly during times of low demand for industrial goods.
Housing and sanitation were problems since towns were growing
rapidly. Liberals and radicals searched for solutions to these issues'''

r.extract_keywords_from_text(mytext)

r.get_ranked_phrases()

r.get_ranked_phrases_with_scores()



